# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: python
  state_top:
    base:
      "*":
        - python

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        python.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - python
  
  - name: custom2
    provisioner:
      pillars-from-files:
        python.sls: pillar-custom2.sls
      pillars:
        top.sls:
          base:
            "*":
              - python
